### ISSUE TITLE
Проблема с установкой TRIK-Studio на macOs Big Sur. 

### ISSUE THREAD

**Issue by daneel-lednikov** [trikset/trik-studio#1026]
Устанваливаю trik-studio на Big Sur. Такая ошибка:
`Ошибка во время процесса установки (ru.qreal.root): Не удалось исполнить (неожиданный код завершения: 6): «/Users/lednikov/TRIKStudio/TRIK Studio.app/Contents/MacOS/trik-studio --clear-conf»`

При нажатии `повторить` все тоже самое, если пропускаю - устанавливается, но не запускается. 
ОС: Big Sur Beta 20A4300b

**Comment by iakov** [comment]
Проверьте, пожалуйста, https://dl.trikset.com/ts/fresh/installer/trik-studio-installer-mac-master.dmg

**Comment by daneel-lednikov** [comment]
Установилось успешно. Запускаю, в доке появляется значок и на этом все. Окна программы нету, не запускается.

**Comment by iakov** [comment]
@daneel-lednikov , попробуйте, пожалуйста, свежую сборку https://dl.trikset.com/ts/fresh/installer/trik-studio-installer-mac-master.dmg 
Лучше из терминала запустить `"$HOME/TRIKStudio/TRIK Studio.app/Contents/MacOS/trik-studio"`. Интересно, что будет выведено в окно терминала.

**Comment by iakov** [comment]
Fixed for 2020.6
