### ISSUE TITLE
Allow spaces in installation path of TS

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/trik-studio#1069]
For now, spaces in path are depricated by installer

**Comment by iakov** [comment]
Раньше были проблемы с пробелами в пути. По-моему, с вызовом компилятора для NXT. Похоже, что это поправили, но ещё в чём-то могли остаться проблемы. Думаю, что сейчас можно разрешить пробелы в инсталляторе, а потом разберёмся.

**Comment by iakov** [comment]
Fixed in https://github.com/trikset/trik-studio/commit/fcac155c40d2eb7d144965397425040a5dd1b339 for 2021.1
