### ISSUE TITLE
Python import doesn't work properly 

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/trik-studio#1137]
Suppose there are two files:

1. run.py:
```
import main
x()
```

2. main.py
```
def x():
    print('A')
```

When someone changes the printing string in `main.py` and rerun `run.py`, script output isn't changed. It seems that the module can not be re-imported when script is rerun.

**Comment by khodand** [comment]
Fixed by this https://github.com/trikset/trikRuntime/pull/655/commits/322d4d332433b43d73e01bc34d352017a8fd8318

**Comment by iakov** [comment]
Fixed in 2021.2
