### ISSUE TITLE
Cannot flash NXT brick

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#1147]
Actually, there is "Couldn't compute FAST_CWD pointer" in logs. Seems like it is an obsolete cygwin1.dll
I suggest to update nxt-tools pack, or even make an attempt to shift to mingw/MSYS2 provided tools.

**Comment by IKhonakhbeeva** [comment]
Ждем ответа пользователя, пропала ли проблема после #1149

**Comment by iakov** [comment]
Fixed in #1149 . Open another issue in case of regression.
