### ISSUE TITLE
TRIK simulator integration for IDEs doesn't show errors and robot console

### ISSUE THREAD

**Issue by evsey9** [trikset/trik-studio#1163]
The tool to run 2D models from other IDEs does not show errors and the robot console. Using the CMD file that I edited myself: https://github.com/evsey9/improved-trik-external-simulation-tool 
Running TRIK Studio 2020.5, Win10 x64, running 2D model from PyCharm Community Edition 2020.2

**Comment by anastasiia-kornilova** [comment]
@evsey9 , could you specify in more detail what behavior you expect? Preferably with examples.

**Comment by evsey9** [comment]
> 
> 
> @evsey9 , could you specify in more detail what behavior you expect? Preferably with examples.

the behavior I expect is the simulator showing robot's console and error output at the bottom of the screen, like in TRIK Studio simulator, which it doesn't do right now, meaning that if a runtime error happens - you wouldn't even be able to know how and where it happened.

**Comment by evsey9** [comment]
issue fixed by adding --console flag to the TRIK simulator tool script
