### ISSUE TITLE
Imported python files do not see TRIK builtins

### ISSUE THREAD

**Issue by evsey9** [trikset/trik-studio#1165]
When you import a python file into the file you are executing (at least in the simulator) using import, that file will not be able to use any of the builtins like brick, script, getPhoto() etc.

Running TRIK Studio 2020.5 on Win10 x64

**Comment by khodand** [comment]
As a workaround, until this bug fixed, try to implement TRIK builtins into your module. Something like that:
```python
import mymodule
mymodule.script = script
mymodule.brick = brick
```

**Comment by khodand** [comment]
Closed with https://github.com/trikset/trikRuntime/pull/655

Now, to use TRIK builtins in custom modules:
```python
import TRIK
from TRIK import *
```
