### ISSUE TITLE
Missing brake mode for Stop motors block

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#117]
In Javascript we have `brake()` method for motor, but no way to use it from Stop Motors block.

**Comment by iakov** [comment]
Boolean flag "Brake" should be enough. It should brake for 300-500 ms, and then turn motors off. Seems like this flag should be turned on by default, but not in this version.

**Comment by anastasiia-kornilova** [comment]
Attention! Check compatibility.

**Comment by iakov** [comment]
#271 is for TRIK

**Comment by iakov** [comment]
Fixed in #271
