### ISSUE TITLE
Open files using TS by default doesn't work properly

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/trik-studio#125]
При открытии некоторых файлов через ассоциированное приложение TRIK Studio
запускается, но сам файл не открывается. Приходится открывать через TRIK Studio.
Надо исправить. Проблема в путях – это происходит при наличии пробелов и
русских букв в названиях папок.

**Comment by IKhonakhbeeva** [comment]
Не получилось воспроизвести
Открывала такой файл:
C:\TRIKStudio\examples\trik\Новая папка\aroun The Corner.qrs

Версия 19.03-33-g36e81f
Инсталлятор Qt IFW 3.0.6
