### ISSUE TITLE
Junior: support animation for robot

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#1280]
Add 4 different sprites for different directions.
 * Use default one for the initial image or if animation is not required
 * Use the same image after step move if no specialized sprite is provided (leave sprite unchanged)
 
 Cases: 
 1. a cat with two images -- heading west or east
 1. a car -- heading N,W,E,S
 1. A ghost -- no animation, single sprite

**Comment by IKhonakhbeeva** [comment]
Fixed in #1302
