### ISSUE TITLE
Python autocomplition in text editor

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/trik-studio#137]
Now it has some problems to support:

QMetaType::registerTypedef: -- Type name 'QObjectList' previously registered as typedef of 'QObjectList' [1069], now registering as typedef of 'QList<QObject*>' [1193].
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread
QObject::setParent: Cannot set parent, new parent is in a different thread 

https://github.com/trikset/trik-studio/pull/136

**Comment by iakov** [comment]
Fixed in #524 Now the same core functionality is used for both JS and Py
