### ISSUE TITLE
Некорректные название действий в "Коллекции подпрограмм".

### ISSUE THREAD

**Issue by ilaforer** [trikset/trik-studio#139]
![2019-04-22_13-35-13](https://user-images.githubusercontent.com/47823664/56496802-9d4eb880-6503-11e9-8658-4fce9983be27.png)

Предлагаю заменить везде Экспортировать на Сохранить, Импортировать на Загрузить.

**Comment by iakov** [comment]
@shirokolobov, @ilyashir, @anastasiia-kornilova , надо дружно посмотреть на менюшки и сразу всё переименовать, а не только эти.
