### ISSUE TITLE
При печати неверный кегль

### ISSUE THREAD

**Issue by ilaforer** [trikset/trik-studio#140]
![image](https://user-images.githubusercontent.com/47823664/56502033-ae0a2900-6519-11e9-9438-c6fbf8090db2.png)

**Comment by iakov** [comment]
На линуксе нормально работает. Печатает в PDF и на принтер. Перейдём на Qt 5.12, потом посмотрим.

**Comment by IKhonakhbeeva** [comment]
Винда с 5.12 работает, но сетка разъезжается
![image](https://user-images.githubusercontent.com/43929571/58297888-1df22480-7de2-11e9-9732-ded514e1e888.png)

А вот проблемы с размером шрифта и на линуксе проглядывают
![image](https://user-images.githubusercontent.com/43929571/58297916-382c0280-7de2-11e9-8b40-4a57bc703b4f.png)

**Comment by iakov** [comment]
А при печати в PDF всё нормально или проблема воспроизводится?

**Comment by IKhonakhbeeva** [comment]
На винде даже не вижу пункта "печать в пдф"
Посмотрю, поиграюсь с настройками, вроде как работа с принтером идет примитивно стандартно-кутешная, так что странно

**Comment by IKhonakhbeeva** [comment]
На линуксе и макосе QPrintDialog используется системный, который не знает о кутешной возможности печатать в файл. Так что нужна отдельная кнопка, если печать в пдф необходима.

> On Windows and macOS, the native print dialog is used, which means that some QWidget and QDialog properties set on the dialog won't be respected

При печати в пдф (винда) поведение аналогично линуксу.
