### ISSUE TITLE
Креш при вызове "Заменить на" для блока с односторонними связями

### ISSUE THREAD

**Issue by ilaforer** [trikset/trik-studio#142]
Когда на сцене Редактора удаляешь один блок через правую кнопку мыши,а потом пытаешься использовать "Заменить на" происходит креш.

**Comment by iakov** [comment]
@ilaforer  Странное описание, наверное, креш?

**Comment by IKhonakhbeeva** [comment]
Креш после попытки заменить элемент, который был связан с удаленным элементом

https://github.com/trikset/trik-studio/blob/master/qrgui/editor/editorViewScene.cpp#L709

Возможно, после удаления не с чем сделать reConnectLink?

**Comment by ilaforer** [comment]
Нужно пояснять? Я завтра буду на ММ, могу зайти.

**Comment by ilaforer** [comment]
Это воспроизводится, когда к заменяемому блоку есть входящая красная стрелочка (связь без источника).

**Comment by IKhonakhbeeva** [comment]
Если есть исходящая красная стрелочка - тоже креш
