### ISSUE TITLE
Win7 - нет платформы TRIK

### ISSUE THREAD

**Issue by ilaforer** [trikset/trik-studio#143]
Программы открываются, но такой платформы нет в настройках.
При открытии программ для TRIK пропадает выбор модели 2D, генерации и т.д.

![win7_330rc1_bag_01](https://user-images.githubusercontent.com/47823664/56513382-f84fd200-653a-11e9-8c22-1a84278d7967.png)

**Comment by IKhonakhbeeva** [comment]
Please try the latest version
![trik-studio-win7 1](https://user-images.githubusercontent.com/43929571/56803741-262f6200-682c-11e9-93c8-20e79b7235e8.png)

**Comment by IKhonakhbeeva** [comment]
На чистой машине баг тоже не воспроизводится

**Comment by ilaforer** [comment]
Надо уточнить у Ильи на какой версии это было. Он нашел этот баг.

**Comment by ilaforer** [comment]
Это было на какой-то бете. В последней версии проблема не появляется.

**Comment by iakov** [comment]
@IKhonakhbeeva надо проверить 2019.1 в чистом окружении Win7.
