### ISSUE TITLE
В TRIK Studio 3.3.0-rc8 не открывается сейв alongTheLine. Студия просто вылетает.

### ISSUE THREAD

**Issue by ilaforer** [trikset/trik-studio#147]

**Comment by ilaforer** [comment]
Регресс относительно 3.2.0

**Comment by IKhonakhbeeva** [comment]
alongTheLine имеет две диаграммы, если одну из них удалить (открыв в 3.2.0), то получившаяся qrs-ка открывается последней версией

**Comment by IKhonakhbeeva** [comment]
Что это за странные "моторы вперед" на второй диаграмме? Подсвечиваются серым, а если их заменить на те, которые есть в списке - попытка открыть крашится позже.

**Comment by IKhonakhbeeva** [comment]
Если установлен nxt, то все работает

**Comment by IKhonakhbeeva** [comment]
3.2.0 в инсталлере по умолчанию ставит nxt, без них на 3.2.0 так же падает

**Comment by iakov** [comment]
- [ ] Для фикса -- только обновить qrs в примерах. Осторожно с локалью, на которой делается qrs: 
 лучше английская.
 - [ ] Отдельно надо разобраться, почему креш, а не сообщение об ошибке, что не установлен плагин. Можно сделать отдельным issue, это можно НЕ в 19.04
 - [ ] Проблемы инсталлятора, что он плохо добавляет плагины -- отдельным issue, и не 19.04
