### ISSUE TITLE
На Win 10 с дефолтной темой не видно чекбокс

### ISSUE THREAD

**Issue by ilaforer** [trikset/trik-studio#153]
![2019-04-30_19-45-15](https://user-images.githubusercontent.com/47823664/56978615-93baf580-6b80-11e9-977f-252457801e04.png)

**Comment by iakov** [comment]
@IKhonakhbeeva , a с Qt 5.11/5.12 тоже так выглядит на win10?

**Comment by IKhonakhbeeva** [comment]
Qt 5.11 - версия с триковского сервера - да, так же

**Comment by iakov** [comment]
@IKhonakhbeeva , проверь, плиз, на новом микро-проекте, всё ли хорошо у темы Fusion. Её можно применить примерно так `QApplication::setStyle(QStyleFactory::create("Fusion"));`. Просто для чистоты эксперимента.
