### ISSUE TITLE
Не запускается master-build (macOS)

### ISSUE THREAD

**Issue by 5h15h4k1n9** [trikset/trik-studio#1554]
## Описание
В [master-версии](https://dl.trikset.com/ts/fresh/installer/trik-studio-installer-mac-master.dmg) TRIK Studio для macOS (от 2022-06-24) поменялась версия QtCore framework, которая требует библиотеки, изначально не предустановленные на устройстве. В связи с этим программа не запускается.

Проверялось на **macOS 12.4 Monterey** на процессоре **Apple Silicon M1**.

### Вызов `otool` на версии 2022.1:
<img width="1165" alt="Снимок экрана 2022-07-09 в 21 26 59" src="https://user-images.githubusercontent.com/71883204/178118407-397ffb43-cfa4-4d6f-8a84-c4b1c5316bbb.png">

Версия фреймворка: **5.15.2**

### Вызов `otool` на master-build:
<img width="1165" alt="Снимок экрана 2022-07-09 в 21 28 03" src="https://user-images.githubusercontent.com/71883204/178118442-408ddcaf-8b9d-4ff4-b392-43418a291092.png">

Версия фреймворка: **5.15.5**
Новые зависимости: 
```
/usr/local/opt/pcre2/lib/libpcre2-16.0.dylib (compatibility version 12.0.0, current version 12.0.0)
/usr/local/opt/glib/lib/libgthread-2.0.0.dylib (compatibility version 7201.0.0, current version 7201.2.0)
/usr/local/opt/glib/lib/libglib-2.0.0.dylib (compatibility version 7201.0.0, current version 7201.2.0)
/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 11.0.0, current version 11.0.0)
```

**Comment by iakov** [comment]
Fixed in #1563
