### ISSUE TITLE
Placing a subprogram block on macOS causes crash

### ISSUE THREAD

**Issue by georgiy-belyanin** [trikset/trik-studio#1708]
Dropping down a subprogram block on macOS causes an almost instant studio crash

Screencast:
https://github.com/trikset/trik-studio/assets/33698739/6ba55e78-e26a-4364-b908-6231f82d292b

[Crash log file](https://github.com/trikset/trik-studio/files/14547108/crash.log)

**Comment by iakov** [comment]
fixed in #1746
