### ISSUE TITLE
libusb -- use system-provided or build from sources

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#18]
- [x] on GNU/Linux we use system-provided already.
 - [x] Msys2/Mingw has libusb package, just use it for both 32 and 64 bit builds
 - [x] on macOS there is libusb 1.0.22 in Homebrew too (available via pkg-config)
 - [x] purge thirdparty/libusb
 - [x] PROFIT!!!!
No need to have a  submodule for https://github.com/libusb/libusb. 

WARNING: just use 
```
CONFIG += link_pkgconfig
PKGCONFIG += libusb-1.0
``` 
instead of direct linking with libusb

**Comment by iakov** [comment]
Для Мака надо не забыть подправить скрипт трависа, добавить  libusb в список устанавливаемых пакетов https://github.com/trikset/trik-studio/blob/master/buildScripts/travis/install.sh#L5

**Comment by iakov** [comment]
В докере потом надо обновить libusb, а то там очень старая тоже. Надо просто собирать с гитхаба, это легко, парой строчек. Но лучше это вынести в отдельный issue, это ждёт.

**Comment by IKhonakhbeeva** [comment]
Мак и винда закрыты в #210 
Докер обновлен [этим](https://github.com/trikset/trikRuntime/commit/1048017c6714164daa6aa4f3987e508c4d69f5c8) коммитом
