### ISSUE TITLE
Смещается палитра и редактор свойств при открытии студии

### ISSUE THREAD

**Issue by ilaforer** [trikset/trik-studio#180]
![image](https://user-images.githubusercontent.com/47823664/57699484-7eee5f80-7660-11e9-95f6-67f6dd04fea5.png)

Воспроизводится на квадратных мониках и на вин 7 и на вин 10. Лечится вот этой кнопкой 

![image](https://user-images.githubusercontent.com/47823664/57699558-acd3a400-7660-11e9-8c2d-7929a5cc57a0.png)

**Comment by ilaforer** [comment]
Должно быть вот так 
![image](https://user-images.githubusercontent.com/47823664/57699637-dab8e880-7660-11e9-9ff6-28cb563c4f18.png)

**Comment by iakov** [comment]
После #177 посмотрим. Нужно уметь воспроизводить ещё стабильно этот баг.

**Comment by iakov** [comment]
@ilaforer , посмотри на новом билде, пожалуйста. Воспроизводится ли https://dl.trikset.com/ts/fresh/installer/trik-studio-installer-master-i686.exe Это сложно отлавливаемая проблема.

**Comment by IKhonakhbeeva** [comment]
Воспроизводится стабильно на виртуалке с квадратными настройками экрана

![image](https://user-images.githubusercontent.com/43929571/58681964-7479d880-8377-11e9-94e9-d4ce3755b728.png)
После "свернуть в окно - развернуть":
![image](https://user-images.githubusercontent.com/43929571/58681978-822f5e00-8377-11e9-8177-23f4a4f0627b.png)

**Comment by iakov** [comment]
@IKhonakhbeeva ,  не бывает "квадратных настроек", бывает "выставлен такой-то графический режим". Какой режим?

**Comment by IKhonakhbeeva** [comment]
Разрешение 800х600
Ситуация как на первых скринах в этом ишью - 1280х1024
