### ISSUE TITLE
Не двигаются банки и мячи в сохраненном упражнении

### ISSUE THREAD

**Issue by ilaforer** [trikset/trik-studio#187]
Если сохранить как упражнение и поставить галочку напротив неизменяемого полигона, в этом упражнении не будут двигаться банки и мячи. Воспроизводится на реальной физике.

**Comment by iakov** [comment]
Потому что опция "Real physics" не сохраняется. Это дубликат/следствие к #75

**Comment by iakov** [comment]
Fixed in #466
