### ISSUE TITLE
Add deployment steps in CI to get fresh installers

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#19]
Build artifacts are useful too as compressed archives, but also installers are definitely missing.

**Comment by iakov** [comment]
Not finished yet.

**Comment by iakov** [comment]
You can split this issue to separate issues for different target platforms, then reference new issues from this one and close the issue.

**Comment by iakov** [comment]
We need window automated installer build for 19.04, but other platforms later (as separate issues).

**Comment by IKhonakhbeeva** [comment]
Auto-build installer:
- [ ] Windows
- [ ] Linux
- [ ] macOS

Auto-deploy installer:
- [ ] Windows
- [ ] Linux
- [ ] macOS

**Comment by iakov** [comment]
Closing, macOS issue is #270
