### ISSUE TITLE
На EV3 в TRIK Studio 2019 2 блока называется по-английски

### ISSUE THREAD

**Issue by ilaforer** [trikset/trik-studio#191]
![image](https://user-images.githubusercontent.com/47823664/58089846-7e107d00-7bce-11e9-9ff0-9ed883e470a2.png)

**Comment by ilaforer** [comment]
Описание на англ только на wait for range sensor

**Comment by iakov** [comment]
Надо посмотреть и другие конструкторы, мб что-то лезет тоже.
