### ISSUE TITLE
Не работает генератор случайных чисел на EV3 в 320, 330рс8, 2019

### ISSUE THREAD

**Issue by ilaforer** [trikset/trik-studio#192]

**Comment by anastasiia-kornilova** [comment]
Не работает, если не проинициализировать переменную, в которую нужно сохранять значение сгенированное рандомайзером. Если переменную проинициализировать, то все ок.

**Comment by anastasiia-kornilova** [comment]
Вот так все работает
![image](https://user-images.githubusercontent.com/8670331/58939200-5816db00-877f-11e9-9b6d-c5a765037afe.png)
