### ISSUE TITLE
Во время остановки выполнения программы, в генерации питон, выскакивает ошибка

### ISSUE THREAD

**Issue by ilaforer** [trikset/trik-studio#200]
![image](https://user-images.githubusercontent.com/47823664/58101758-d8b6d280-7be8-11e9-9d04-6c0f045385c9.png)

**Comment by ilaforer** [comment]
Воспроизводится не всегда. Пока не понимаю зависимость.

**Comment by anastasiia-kornilova** [comment]
Это проблема прошивки, надо перенести в trikRuntime.
