### ISSUE TITLE
qrxc: not stable order of XML attributes

### ISSUE THREAD

**Issue by IKhonakhbeeva** [trikset/trik-studio#238]
Магия с фиксированным elements.h немного не до конца работает

![](https://user-images.githubusercontent.com/43929571/58681528-72167f00-8375-11e9-95d5-3241f7689f1b.png)

**Comment by iakov** [comment]
Это Qt 5.12 MinGW 7.3  различия Debug & Release сборок?

**Comment by IKhonakhbeeva** [comment]
Это различия того, что сейчас лежит в репо и результата после любой сборки Qt 5.12 mingw7.3 debug/release x86/x64
Порядок того, что получается - не фиксирован и гуляет от сборки к сборке

**Comment by iakov** [comment]
Ну вот есть такая проблема, да. И это проблема Qt, потому что не поддерживают normalized XML. https://bugreports.qt.io/browse/QTBUG-47566

**Comment by iakov** [comment]
Пишут в документации, что надо лишь 0 выставить, что мы и делаем перед вызовом qrxc. https://doc.qt.io/qt-5/qhash.html#algorithmic-complexity-attacks

**Comment by iakov** [comment]
@IKhonakhbeeva как оно сейчас после #257  ? Стало лучше?

**Comment by IKhonakhbeeva** [comment]
Больше подбной ситуации не возникало
