### ISSUE TITLE
Opening the lastSafeCode.js when opening another js project but not saved previous js project.

### ISSUE THREAD

**Issue by ilyashir** [trikset/trik-studio#27]
Когда js проект не сохранен и открываются другие js проекты, тогда с ними же открывается файл lastSaveCode.js с содержанием первого открытого несохраненного проекта.

**Comment by ilyashir** [comment]
![lastsavecode](https://user-images.githubusercontent.com/941354/53302680-0bfbf680-3872-11e9-8a67-64655539758d.png)

**Comment by IKhonakhbeeva** [comment]
Не получилось воспроизвести.
Возможно, неправильно поняла.
@ilyashir , недавно произошли изменения, связанные с открытием/закрытием файлов. На последней версии баг сохранился? Если да, можно немного более подробную инструкцию, как можно повторить баг?

**Comment by IKhonakhbeeva** [comment]
@ilyashir , please try version from #164. You can get it from appveyorBot's comment.
