### ISSUE TITLE
Textual interpretation, no observable variables at all

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/trik-studio#28]

**Comment by anastasiia-kornilova** [comment]
At the right menu during textual interpretation variables are not updated.

**Comment by anastasiia-kornilova** [comment]
Энкодеры, гироскоп, акселерометр обновляют значения. Датчики нет.

**Comment by anastasiia-kornilova** [comment]
Все работает, если в начале запустить на 2Д модели.

**Comment by iakov** [comment]
Fixed in #284
