### ISSUE TITLE
Регресс: в режиме 2Д не сбрасывается энкодер

### ISSUE THREAD

**Issue by ssloy** [trikset/trik-studio#280]
Машинка должна проехать вперёд и развернуться. При свежезапущенной студии в первый раз всё отрабатывает, потом перестаёт работать разворот. Причина - не сбрасывается значение энкодера. Причём если после сброса энкодера воткнуть блок задержки, даже с нулевым временем, то всё прекрасно отрабатывает.

[clear-encoder-bug.zip](https://github.com/trikset/trik-studio/files/3290835/clear-encoder-bug.zip)

**Comment by anastasiia-kornilova** [comment]
It seems that source of this problem lies in this fix -- https://github.com/trikset/trik-studio/commit/14e0eb882908619b7b948ca3e2dc52be94e26851
