### ISSUE TITLE
Не расширяется сцена

### ISSUE THREAD

**Issue by shirokolobov** [trikset/trik-studio#289]
Рисуем стену за границу сцены, сцена не расширяется. Только уменьшив масштаб, можно посмотреть нарисованную стену.

![2019-06-18_12-10-18](https://user-images.githubusercontent.com/9254967/59673105-61fdfc80-91c9-11e9-9d62-dbd3f19ead1d.png)

**Comment by iakov** [comment]
Это не регресс.
С рисованием много мелких проблем, конечно. Пример того, что надо делать (чтобы пофиксить) есть в коде перетаскивания робота: сцена ресайзится и робота нельзя поставить на стену. А вот банки и мячи можно. В общем, есть что править.
