### ISSUE TITLE
Backward  compatibility for DC-motor brake mode

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#308]
После #117 (но относится и к #223, #227) , если загрузить старую программу с "Моторы стоп" генерируется код с "brake()". Это значит, что примеры, созданные в рамках предыдущих версий, у пользователей отъедут, например, потому что для brake на роботе нужно вставлять еще и задержку. Надо как-то чинить. Вариант -- попробовать при загрузке, в конверторе сейвоф выставлять float.

**Comment by anastasiia-kornilova** [comment]
Fixed in #310
