### ISSUE TITLE
Иконки для функции "Заменить на..."

### ISSUE THREAD

**Issue by ilaforer** [trikset/trik-studio#382]
Предлагаю добавить небольшие иконки в список блоков функции "заменить на..." 
![2019-07-16_12-39-40](https://user-images.githubusercontent.com/47823664/61284173-1e49e300-a7c7-11e9-94a2-370289c3db06.png)

**Comment by iakov** [comment]
QLabel умеет делать QPixmap. Или это горизонтальный layout с иконкой  и текстом (если так правильнее вдруг. (иконки у всех блоков есть).
