### ISSUE TITLE
Наименование блока «Функция» изменить на «Выражение» (+ иконку изменить)

### ISSUE THREAD

**Issue by shirokolobov** [trikset/trik-studio#400]

**Comment by iakov** [comment]
@shirokolobov, нужна иконка. ;)

**Comment by shirokolobov** [comment]
> @shirokolobov, нужна иконка. ;)

Мы не так договаривались :)

**Comment by shirokolobov** [comment]
https://www.google.com/search?newwindow=1&biw=1920&bih=888&tbm=isch&sa=1&ei=4hYvXb7HF_CLmwXu7qDgBA&q=icon+code&oq=icon+code&gs_l=img.3..0j0i30j0i5i30l8.39284.41372..42246...0.0..0.52.447.9......0....1..gws-wiz-img.......0i67.qbr6Az8KMk4

**Comment by iakov** [comment]
#423
