### ISSUE TITLE
Reuse correct functions from trikRuntime

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/trik-studio#422]
https://github.com/trikset/trik-studio/pull/421 -- this PR is an example of bad practice about copying code from trikRuntime.

**Comment by khodand** [comment]
We have [utilites class](https://github.com/trikset/trikRuntime/pull/465) now, so we should make him accessible from studio code and then use it

**Comment by iakov** [comment]
#421 intorduces bugs, this code is fixed in trikRuntime.
