### ISSUE TITLE
Loss of object restangle when loading virtual model.

### ISSUE THREAD

**Issue by ilyashir** [trikset/trik-studio#43]
Пропадает объект прямоугольник при загрузки виртуальной модели мира.
[model.xml.txt](https://github.com/trikset/trik-studio/files/2940726/model.xml.txt)

**Comment by ilyashir** [comment]
При загрузке не правильно координаты пересчитывает. 
Если прямоугольник был задан как `<rectangle begin="50:50" end="10:10">` -- все отлично
Если  `<rectangle begin="50:50" end="100:100">` -- сворачивается в точку.

**Comment by anastasiia-kornilova** [comment]
Не воспроизводится на Линуксе.

**Comment by anastasiia-kornilova** [comment]
Первое. Проблема в нецелочисленных значениях begin и end. Нецелочисленные сворачиваются в 0.
