### ISSUE TITLE
Добавить функциональность для работы с фоном

### ISSUE THREAD

**Issue by shirokolobov** [trikset/trik-studio#508]
Добавить возможность:
- [x] Ресайзить добавленную картинку.
- [x] Двигать добавленную картинку.
Может быть,  научиться добавлять несколько картинок.

**Comment by IKhonakhbeeva** [comment]
Двигать можно после даблклика по фону

**Comment by iakov** [comment]
@shirokolobov , поскольку всё делать можно, закрываю баг.
