### ISSUE TITLE
Залипание иконок на курсоре

### ISSUE THREAD

**Issue by NastenkaMeretskaya** [trikset/trik-studio#517]
https://drive.google.com/open?id=1WZjQqcMOhqTNqvAMy55TSTdTSxp60gxk

**Comment by NastenkaMeretskaya** [comment]
[qreal.log](https://github.com/trikset/trik-studio/files/3615751/qreal.log)
[actions.log](https://github.com/trikset/trik-studio/files/3615752/actions.log)

**Comment by IKhonakhbeeva** [comment]
2. Надо более четкую последовательность действий для воспроизведения. Иногда мелькает, но пока что не понятно, как повторить.

**Comment by NastenkaMeretskaya** [comment]
Ага, спасибо!

вт, 24 сент. 2019 г., 20:31 IKhonakhbeeva <notifications@github.com>:

**Comment by NastenkaMeretskaya** [comment]
А, я тупняк.
Нужно описать, как повторить?

вт, 24 сент. 2019 г., 20:40 Anastasiya Meretskaya <meretskaya@trikset.com>:

**Comment by IKhonakhbeeva** [comment]
Да, а то очень рандомный (вроде) баг, не получается его отловить нормально
