### ISSUE TITLE
Annoying naming schema for EV3

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#519]
Если название файла оканчивается на цифру, при формировании байткода возникает дополнительная сквозная нумерация. Ее надо убрать, слишко много файлов загрузится на контроллер.
Например, имя файла - f02.qrs. Формируем байткод f02.lms и загружаем его на EV3. Все нормально. Затем вносим изменения в диаграмму, закрываем сформированное окно байткода и снова генерируем его. Получается f021.lms. Затем f022.lms. И так далее.

**Comment by IKhonakhbeeva** [comment]
Новый номер будет только если сформированный код изменяли (и сохраняли). Иначе заменится предыдущий сохранённый (с, возможно, важными ручными изменениями) вариант.

Предложение: если хочется сохранить изменённую lms, всегда надо выдавать окно сохранения в новое место, а не автоматически сохранять в appdata (где оно изначально лежит после создания)
Или при кодогенерации спрашивать, заменить ли старый вариант.

В общем, надо обсуждать поведение

**Comment by iakov** [comment]
Ок, пока признаем "не ошибкой": не надо пытаться править код ручками.
