### ISSUE TITLE
PlayTone hangs on EV3

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#537]
При использовании умножения в частоте звукового сигнала программа на EV3 виснет (2019.6) [hhh.qrs.zip](https://github.com/trikset/trik-studio/files/3651301/hhh.qrs.zip)

**Comment by anastasiia-kornilova** [comment]
Проблемы с умножением нет, поигралась на разных значениях на этом примере
[soundMult.qrs.tar.gz](https://github.com/trikset/trik-studio/files/3678404/soundMult.qrs.tar.gz)

**Comment by anastasiia-kornilova** [comment]
Кароче, @iakov , эту багу закрываем, это проблема с передаваемыми параметрами в подпрограмму.

**Comment by iakov** [comment]
В данном случае в подпрограмме используется неинициализированная переменная, а надо передавать.
