### ISSUE TITLE
Проблема с фоновым изображением (не подгружается)

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#579]
> "При загрузке модели мира фоновое изображение не подгружается, хотя лежит в той же папке."

**Comment by IKhonakhbeeva** [comment]
А разве должно?
Фон - такая же картинка, его надо либо сохранять в сейв, либо искать по указанному при создании пути (а не "в той же папке")
Возможно, недопонимание из-за того, что у в "настройки" фона сложнее зайти и непонятно, что там тоже есть галочка "сохранять в сейв".

Предложение: фон сделать автоматически сохраняемым в сейв (сейчас по умолчанию сохраняется только путь до картинки)

**Comment by iakov** [comment]
Давай всегда картинки (и фон) по умолчанию сохранять. Пусть галочка/опция будет включена по умолчанию. А то нам будут присылать сейвы с программами, в которых картинок нет.
