### ISSUE TITLE
2D model scene drawing issues

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#600]
На Убунту 16.04 (вдруг на винде всё хорошо)
> При рисовании. Выбрать стрелочку, потом кликнуть объект на сцене, потом выбрать банку или мяч, или другой курсор, но на сцене будет кулак. Если нажать эскейп, то будет стрелка с банкой.

> Мячи можно ставить на банки и наоборот.
> Робота можно поставить на мяч и на банку

**Comment by IKhonakhbeeva** [comment]
По эскейпу стрелка не меняется (не получилось воспроизвести).
Получилось воспроизвести только то, что кулак менялся на нужную стрелку только после первого рисования. Это пофиксила.
