### ISSUE TITLE
timeline не соответствует реальному течению времени

### ISSUE THREAD

**Issue by IKhonakhbeeva** [trikset/trik-studio#614]
Если запустить таймер на 20000 миллисекунд, то диаграмма и js ждут на самом деле 14-15 секунд (то есть время модели бежит куда быстрее).
Хочется, чтобы 100% скорость соответствовала реальности

**Comment by iakov** [comment]
Дело в том, что модель живёт в своём мире, где своё время. Никакой синхронизации с реальным нет, потому что это как раз нужно для точного моделирования. Справа вверху как раз рисуется "внутренний секундомер мира". На быстрых компьютерах он успевает обсчитать сильно быстрее реального времени. Для пользователя анимация рисуется с задержкой, чтобы было приятнее смотреть.  

В силу особенностей реализации имитационной модели предлагаю не считать это ошибкой. Если очень будет раздражать, можно чуть поправить коэффициенты для "среднего типичного компьютера". Можно даже попробовать автоматически подбирать "коэффициент продуктивности" конкретного компьютера.
