### ISSUE TITLE
EV3 US-sensor problem

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#621]
> При выводе на экран EV3 показаний ультразвукового датчика расстояния, робот выводит 0 в новой версии Trik Studio 2019.7 и правильное значение в старой (например в 3.3.0-B1)
[Bug_37-20191106T085215Z-001.zip](https://github.com/trikset/trik-studio/files/3813411/Bug_37-20191106T085215Z-001.zip)

**Comment by IKhonakhbeeva** [comment]
Dublicate #603
Fixed in #605 
Или это уже на версии после 605?
Или ультразвуковой != просто датчик расстояния? Если так, то не вижу, где его можно установить
