### ISSUE TITLE
2D-model robot configuration is separated from generator configuration

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#622]
> При установке датчика в режиме редактора он не появляеся в режиме 2D-модели. Приходится устанавливать повторно.

**Comment by iakov** [comment]
По-моему, это старая добрая "фича", причина где-то глубоко в архитектуре.

**Comment by IKhonakhbeeva** [comment]
Возможно, я это починила в #629 
В любом случае сейчас оно работает, везде меняется одновременно

**Comment by iakov** [comment]
Да, у меня меняется. Ладно, пока закрываю, будем считать, что всё норм, или мы не можем воспроизвести.
