### ISSUE TITLE
TS silently ignores jpg images

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#626]
> Не загружаются файлы изображений ни как фон, ни как рисунок.
Это поведение при больших картинках. Надо просто как-то предупреждать, лучше даже ругаться с ошибкой или выдавать диалоговое окно с ошибкой.

**Comment by IKhonakhbeeva** [comment]
У меня png в 20 МБ в качестве 4К вполне загружает и как фон, и как рисунок, с предупреждением, что это может заморозить немного процесс выполнения.
Можно сюда скинуть конкретную картинку (или больше подробностей), с которой не работает, может быть?

**Comment by iakov** [comment]
Запросил. Ждём.

**Comment by iakov** [comment]
Вот файл ![Inverse_line_1200x2000](https://user-images.githubusercontent.com/706759/68607912-cd22d500-04c2-11ea-8f58-1cf6c486623b.jpg)
