### ISSUE TITLE
Add timelimit for realtime in checker

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/trik-studio#700]
**Is your feature request related to a problem? Please describe.**
Because our checker checks timelimit using internal time then real time of checking is different between different machines and different load, so we need some constraints on real time

**Describe the solution you'd like**
Add flag-file to checker with time and run every field by timer with specified timer. If the execution doesn't end, go to the next field.

**Comment by iakov** [comment]
Хватит ли просто /usr/bin/timeout, которому как-то передаётся опция?

**Comment by anastasiia-kornilova** [comment]
Да, это именно оно.
