### ISSUE TITLE
Python: script.getPhoto don't work on 2D model

### ISSUE THREAD

**Issue by khodand** [trikset/trik-studio#722]
Using script.getPhoto() at python script and executing it on the 2D model causes the error:

in execMain ValueError: Called getPhoto() -> QVector, return type 'QVector' is ignored because it is unknown to PythonQt. Probably you should register it using qRegisterMetaType() or add a default constructor decorator to the class.

1. Execute this script
``` python
import sys
import time
import random
import math

class Program():
  __interpretation_started_timestamp__ = time.time() * 1000

  pi = 3.141592653589793

  def execMain(self):

    
    print(script.getPhoto())

    return

def main():
  program = Program()
  program.execMain()

if __name__ == '__main__':
  main()

````

![изображение](https://user-images.githubusercontent.com/20268352/73196163-2dc7c280-4140-11ea-8391-3ba4a5c95479.png)

 - OS: Windows

**Comment by iakov** [comment]
Fixed in 2020.1
