### ISSUE TITLE
Stop 2D model by pressing F5

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/trik-studio#724]
Now only running support under F5 button

**Comment by IKhonakhbeeva** [comment]
Везде, где можно запустить по F5 (или Ctrl+F5 для трика), можно остановить по Shift+F5 (аналогично Shift+Ctrl+F5)

Единственное, что это криво работает, когда запускается код, а не блоки. Это можно поправить на Shift+F5, чтобы аналогично работало

**Comment by anastasiia-kornilova** [comment]
Что ты имеешь в виду под "везде"?
Анивей, нужна хоть какая-то вариация. Если она есть, укажи, плиз, как она работает в студии для скриптов.

**Comment by IKhonakhbeeva** [comment]
Для отправки на ev3 работает F5 (+Shift для остановки) и для блоков, и для скриптов
Для отправки на триковского робота (в режиме js и python) работает Ctrl+F5(+Shift для остановки) опять же и для блоков, и для скриптов
Для 2d-режима блочная диаграмма работает на F5(+Shift для остановки) и в режиме Edit, и Debug

Проблема только когда в 2d модели запускаем триковские скрипты. Если открыт Edit, то вообще ни запустить, ни остановить нельзя. Если при этом открыта сама моделька, то сейчас действительно можно только запускать (но локально уже добавила остановку на Shift+F5). На сами скрипты тоже, наверное, попытаться это повесить? Чтобы когда открыт скрипт, его можно было в 2d модели запустить?

**Comment by anastasiia-kornilova** [comment]
Спасибо за развернутый ответ, поняла.

> На сами скрипты тоже, наверное, попытаться это повесить? -- Ага, если это не займет много времени, чтобы не пользователю не делать лишних движений. В любом случае, остановку можешь выкатить сейчас, остальное потом будем приукрашивать.

А еще я не поняла общую логику -- почему где-то без Ctrl, а где-то с ним, причем в модель -- "на роботов отправляем с Ctrl, а локально запускаем в модели без" это не укладывается. Надо либо понять, либо как-то унифицировать.

**Comment by IKhonakhbeeva** [comment]
А вот почему где-то с Ctrl - понятия не имею. Так как никаких событий на просто F5 не повешено, то есть конфликта нет. Может, когда-то давно была глубокая мысль...
