### ISSUE TITLE
Multiple new line with print()

### ISSUE THREAD

**Issue by khodand** [trikset/trik-studio#729]
When using print(), console outputs have few additional newlines.

Deploy your script to the controller and then see your TS console output.
```javascript
var __interpretation_started_timestamp__;
var pi = 3.141592653589793;

var main = function()
{
	__interpretation_started_timestamp__ = Date.now();
	i = 0;
	while (true) {
		print(++i)
		}
	
	return;
}
```
![изображение](https://user-images.githubusercontent.com/20268352/73596613-a1990f00-4534-11ea-9d48-658b04ec37f0.png)

Same problem with python too

**Comment by iakov** [comment]
Fixed in #736
