### ISSUE TITLE
TS slows down after program is run several times

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/trik-studio#755]
Выполнение в студии начинает тормозить после нескольких вызовов одной и той же программы. Лечится -- перезапуском студии.

**Comment by anastasiia-kornilova** [comment]
В архиве два видео-файла. На первом показан первый запуск, на втором -- после 20 запусков программы.
[demo.zip](https://github.com/trikset/trik-studio/files/4219443/demo.zip)

**Comment by iakov** [comment]
Похоже, что исправлено в 2020.5. Переоткроем, если будет встречаться.
