### ISSUE TITLE
При импорте подпрограмм из файла, обнуляется "модель мира" и карта подключений тележки (моторы, датчики).

### ISSUE THREAD

**Issue by BorisADrozdov** [trikset/trik-studio#765]
При импорте подпрограмм из файла, обнуляется "модель мира" и карта подключений тележки (моторы, датчики).
2019.08

**Comment by BorisADrozdov** [comment]
Альтернативное предложение (если прямой путь долгий/сложный) - оставить портирование подпрограмм только через "коллекцию", НО тогда надо сделать Сохранение "Коллекции" в определенный файл чтобы эти коллекции могли быть разными, не затирались при сносе ПО, могли переноситься с проектами, ... .

**Comment by IKhonakhbeeva** [comment]
Fixed in #918
