### ISSUE TITLE
Old version showed

### ISSUE THREAD

**Issue by BorisADrozdov** [trikset/trik-studio#768]
При установке:
- создается ярлык с названием старой версии
- на титульной странице (запуск с ярлыка) - старая версия.

**Comment by iakov** [comment]
Такое ощущение, что при установке не удалилась старая версия. Сбоев при установке не было?

**Comment by BorisADrozdov** [comment]
Удалял начисто, затем устанавливал через инсталлер, через скрипт - всё едино.
И уж точно это никак не влияет на титульную страницу.

**Comment by anastasiia-kornilova** [comment]
@BorisADrozdov, проверьте, куда идёт ярлык, точно ли в новую студию?

**Comment by BorisADrozdov** [comment]
Естественно. Могу всё проверить еще раз.

**Comment by BorisADrozdov** [comment]
![1](https://user-images.githubusercontent.com/61494310/75551066-6101b800-5a44-11ea-97b9-e61fbbdbf03f.jpg)
![2](https://user-images.githubusercontent.com/61494310/75551070-62cb7b80-5a44-11ea-973f-616104d7bb07.jpg)
Это после "чистой" установки - всё удалил через установку/удаление, установил через инсталлер, т.е. ошибка с ярлыком - в инсталлере. С титульной страницей - видимо, в титульной странице :-)

**Comment by anastasiia-kornilova** [comment]
Хм, у версии грязный хвост, откуда её берете?

**Comment by anastasiia-kornilova** [comment]
В общем, то что скидывали в слак и не должно было быть с номером, дали просто текущий срез для проверки функциональности. Версия обновляется тогда, когда её затегировали - заморозили. https://dl.trikset.com/ts/fresh/trik-studio-installer_2020.1-i686.exe - вот эта, кажется, затеганная, попробуйте её

**Comment by BorisADrozdov** [comment]
Да, та, что Яков в Слаке скинул. https://dl.trikset.com/ts/fresh/trik-studio-installer-master-i686-auto.zip
Пробую новую.

**Comment by BorisADrozdov** [comment]
Ярлык - Ок, 
Титульная - Ок
Тикет можно "закрывать".
