### ISSUE TITLE
Incorrect behaviour of encoders in 2D model 

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/trik-studio#78]
При застревании в идеальном мире моторы проворачиваются, нельзя решать задачу о застревании.

**Comment by iakov** [comment]
Надо оставить только те лейблы конструкторов на этом issue, для которых актуально. Если случайно для  ЛЕГО работает, то отложить до 19.06 (сменить майлстоун на исью)

**Comment by anastasiia-kornilova** [comment]
При застревании в идеальном мире моторы проворачиваются, нельзя решать задачу о застревании.

**Comment by IKhonakhbeeva** [comment]
@anastasiia-kornilova А разве неидеальный мир себя корректно ведет?
Насколько я вижу, там тоже энкодеры не останавливаются (или не начинают хотя бы медленнее крутиться)
