### ISSUE TITLE
Incorrect reaction on saving action in close dialog

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/trik-studio#783]
При закрытии приложения, вылазиет окно с вопросом "Сохранить текущий проект?". При нажатии на кнопку "отмена" Trik Studio закрывает твою программу, не сохраняя её.

**Comment by IKhonakhbeeva** [comment]
Это когда с js работаешь?

**Comment by anastasiia-kornilova** [comment]
"Почти всё то, что вы перечислили. 
Если открыт любой js-файл, то при попытке завершения Trik Studio, (хоть нажатием на на кнопку закрытия в правом верхнем углу), появляется окно с вопросом "Сохранить текущий проект?".
В диалоговом окне есть три кнопки: "Сохранить", "Не сохранять", "Отмена".
При нажатии на кнопку "Отмена" Trik Studio закрывает js-файл, не сохраняя его. "

**Comment by BorisADrozdov** [comment]
Как понимаю, ТС вообще все вторичные окна (окромя основного) закрывает (подпрограммы, ЯС, ...) при подобной процедуре. Т.е. надо не закрывать все окна перед выдачей запроса. Или "сечь" изменения в окне ЯС.
