### ISSUE TITLE
Strange draing artifacts when moving objects

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#804]
https://www.youtube.com/watch?v=6O6AAahT5Ds

**Comment by BorisADrozdov** [comment]
2020.1
Сегодня столкнулся с данным эффектом.
Последствия:
- "тележка" так и ушла в "параллельное измерение" и не появлялась после всяких манипуляций.
- датчики продолжали двигаться как ни в чём ни бывало.
Главное:
- Сохраненная после данного инцидента "карта мира" стала приводить к крашу ТС при загрузке.

[3.6 Массивы_тупики отдельно 3v5.zip](https://github.com/trikset/trik-studio/files/4321129/3.6._.3v5.zip)

**Comment by IKhonakhbeeva** [comment]
Последний пункт - все та же проблема со стенами, здесь она никак не влияет
К слову, проблема с крашем уже починена, можно в этом убедиться, скачав последнюю версию студии
