### ISSUE TITLE
Update TRIK examples

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#908]
1. Refresh from 
[examples.zip](https://github.com/trikset/trik-studio/files/4598004/examples.zip)
2. Check with real physics turned on/off

**Comment by khodand** [comment]
![изображение](https://user-images.githubusercontent.com/20268352/81543482-ca744000-937e-11ea-9d96-0f29e5302611.png)

**Comment by khodand** [comment]
В ev3  примерах нет объектов в 2D поле, так задумано?
