### ISSUE TITLE
Patcher leaks

### ISSUE THREAD

**Issue by anastasiia-kornilova** [trikset/trik-studio#915]
Direct leak of 96 byte(s) in 1 object(s) allocated from:
    #0 0x7f227f232448 in operator new(unsigned long) (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libasan.so.4+0xe0448)
    #1 0x7f227ec009c4 in qrRepo::details::Repository::init() (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libqrrepo.so.1+0x2909c4)
    #2 0x7f227ec03385 in qrRepo::details::Repository::Repository(QString const&) (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libqrrepo.so.1+0x293385)
    #3 0x7f227ec5135c in qrRepo::RepoApi::RepoApi(QString const&, bool) (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libqrrepo.so.1+0x2e135c)
    #4 0x55f0560ad16b  (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/patcher+0x916b)
    #5 0x7f227c8cab96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

Indirect leak of 194 byte(s) in 5 object(s) allocated from:
    #0 0x7f227f230b40 in __interceptor_malloc (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libasan.so.4+0xdeb40)
    #1 0x7f227e288abc in QArrayData::allocate(unsigned long, unsigned long, unsigned long, QFlags<QArrayData::AllocationOption>) (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libQt5Core.so.5+0xb3abc)

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f227f230f30 in realloc (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libasan.so.4+0xdef30)
    #1 0x7f227e288b88 in QArrayData::reallocateUnaligned(QArrayData*, unsigned long, unsigned long, QFlags<QArrayData::AllocationOption>) (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libQt5Core.so.5+0xb3b88)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7f227f230b40 in __interceptor_malloc (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libasan.so.4+0xdeb40)
    #1 0x7f227e2e79c0 in QMapDataBase::createNode(int, int, QMapNodeBase*, bool) (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libQt5Core.so.5+0x1129c0)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7f227f232448 in operator new(unsigned long) (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libasan.so.4+0xe0448)
    #1 0x7f227e2e7a9d in QMapDataBase::createData() (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libQt5Core.so.5+0x112a9d)
    #2 0x7f227ecb3fc6 in QMap<QString, QVariant>::insert(QString const&, QVariant const&) (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libqrrepo.so.1+0x343fc6)
    #3 0x7f227ecb9bff in qrRepo::details::Object::setProperty(QString const&, QVariant const&) (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libqrrepo.so.1+0x349bff)
    #4 0x7f227ec01070 in qrRepo::details::Repository::init() (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libqrrepo.so.1+0x291070)
    #5 0x7f227ec03385 in qrRepo::details::Repository::Repository(QString const&) (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libqrrepo.so.1+0x293385)
    #6 0x7f227ec5135c in qrRepo::RepoApi::RepoApi(QString const&, bool) (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/libqrrepo.so.1+0x2e135c)
    #7 0x55f0560ad16b  (/home/anastasiya/Documents/trik/build-studio-Desktop_Qt_5_12_6_GCC_64bit-Debug/bin/debug/trikStudio-checker/bin/patcher+0x916b)
    #8 0x7f227c8cab96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

**Comment by iakov** [comment]
Lots of related problems were addressed by #960
