### ISSUE TITLE
Obsolete WinSCP & Putty are packed into installer

### ISSUE THREAD

**Issue by iakov** [trikset/trik-studio#97]
Proposed solution: 
1. Use direct download from SF for WinScp: https://sourceforge.net/projects/winscp/files/WinSCP/5.15/WinSCP-5.15-Portable.zip/download

2. Use https://winscp.net/download/putty.exe https://winscp.net/download/puttygen.exe for Putty

This allows to avoid cloning https://github.com/qreal/trik-runtime-builds/

**Comment by IKhonakhbeeva** [comment]
Close in #121
